name: BUILD_CHECK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependancies
      run: sudo apt-get install binutils gcc-avr avr-libc uisp avrdude flex byacc bison 
    - name: make
      run: make Build -C project/3_IMPLEMENTATION
